### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by reppard** [Kloadut/dokku-pg-plugin#82]
So I'm just trying to test deploying a bare bones Rails app with a postgresql container linked up.  I keep getting time outs even though the db is up and running.

``` shell
$ dokku version
0.3.26
```

``` shell
$ dokku postgresql:list                                                                                                                                             
PostgreSQL containers:
  - dbtest
```

``` shell
$ dokku config dbtest                                                                                                                                               
=====> dbtest config vars
DATABASE_URL: postgres://root:8MdcAvh9bCCx3As6@172.17.42.1:32778/db
```

``` shell
$ psql -hmydokkuinstance.org -p 32778 -Uroot db
Password for user root: 
psql (9.4.4, server 9.3.7)
SSL connection (protocol: TLSv1.2, cipher: DHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.
db=# \q
```

``` shell
$ dokku run dbtest bundle exec rake db:migrate
X11 forwarding request failed on channel 0
rake aborted!
PG::ConnectionBad: could not connect to server: Connection timed out
        Is the server running on host "172.17.42.1" and accepting
        TCP/IP connections on port 32778?
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `initialize'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `new'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `connect'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:87:in `connection'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:913:in `initialize'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:820:in `new'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:820:in `up'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:798:in `migrate'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Any input at all would be greatly appreciated.  Thanks!

**Comment by atsoy** [comment]
@reppard Hey, i'm not sure, but probably you might have to set DB_PORT etc. manually over dokku config:set ...`.
